In [1]:
# STEP 1: Import Required Libraries
import pandas as pd
import numpy as np

In [2]:
# STEP 2: Load CSV File
df = pd.read_csv('/content/SP 500 ESG Risk Ratings.csv')

In [3]:
# STEP 3: Preview the Data
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

Shape: (503, 15)
Columns: ['Symbol', 'Name', 'Address', 'Sector', 'Industry', 'Full Time Employees', 'Description', 'Total ESG Risk score', 'Environment Risk Score', 'Governance Risk Score', 'Social Risk Score', 'Controversy Level', 'Controversy Score', 'ESG Risk Percentile', 'ESG Risk Level']

,Symbol,Name,Address,Sector,Industry,Full Time Employees,Description,Total ESG Risk score,Environment Risk Score,Governance Risk Score,Social Risk Score,Controversy Level,Controversy Score,ESG Risk Percentile,ESG Risk Level
0,ENPH,"Enphase Energy, Inc.","47281 Bayside Parkway\nFremont, CA 94538\nUnit...",Technology,Solar,"3,157","Enphase Energy, Inc., together with its subsid...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EMN,Eastman Chemical Company,"200 South Wilcox Drive\nKingsport, TN 37662\nU...",Basic Materials,Specialty Chemicals,"14,000",Eastman Chemical Company operates as a special...,25.3,12.8,6.6,5.8,Moderate Controversy Level,2.0,50th percentile,Medium
2,DPZ,Domino's Pizza Inc.,"30 Frank Lloyd Wright Drive\nAnn Arbor, MI 481...",Consumer Cyclical,Restaurants,"6,500","Domino's Pizza, Inc., through its subsidiaries...",29.2,10.6,6.3,12.2,Moderate Controversy Level,2.0,66th percentile,Medium
3,DAY,"Dayforce, Inc.","3311 East Old Shakopee Road\nMinneapolis, MN 5...",Technology,Software - Application,"9,084","Dayforce Inc., together with its subsidiaries,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DVA,Davita Inc.,"2000 16th Street\nDenver, CO 80202\nUnited States",Healthcare,Medical Care Facilities,"70,000",DaVita Inc. provides kidney dialysis services ...,22.6,0.1,8.4,14.1,Moderate Controversy Level,2.0,38th percentile,Medium

In [4]:
# Step 4: Data Cleaning

In [5]:
# Create a copy of the dataset
df_clean = df.copy()

In [6]:
# Drop unneeded columns
df_clean.drop(['Address', 'Description'], axis=1, inplace=True)

In [7]:
# Clean 'Full Time Employees' – remove commas, convert to numeric
df_clean['Full Time Employees'] = df_clean['Full Time Employees'].str.replace(',', '', regex=False)
df_clean['Full Time Employees'] = pd.to_numeric(df_clean['Full Time Employees'], errors='coerce')

In [8]:
# Convert ESG Percentile (e.g., "50th percentile") to numeric
df_clean['ESG Risk Percentile'] = df_clean['ESG Risk Percentile'].str.extract(r'(\d+)', expand=False)
df_clean['ESG Risk Percentile'] = pd.to_numeric(df_clean['ESG Risk Percentile'], errors='coerce')

In [9]:
# Convert ESG Scores to numeric
esg_columns = [
    'Total ESG Risk score',
    'Environment Risk Score',
    'Governance Risk Score',
    'Social Risk Score',
    'Controversy Score'
]
df_clean[esg_columns] = df_clean[esg_columns].apply(pd.to_numeric, errors='coerce')

In [10]:
# Show cleaned data info
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Symbol                  503 non-null    object
 1   Name                    503 non-null    object
 2   Sector                  502 non-null    object
 3   Industry                502 non-null    object
 4   Full Time Employees     498 non-null    float64
 5   Total ESG Risk score    430 non-null    float64
 6   Environment Risk Score  430 non-null    float64
 7   Governance Risk Score   430 non-null    float64
 8   Social Risk Score       430 non-null    float64
 9   Controversy Level       430 non-null    object
 10  Controversy Score       403 non-null    float64
 11  ESG Risk Percentile     430 non-null    float64
 12  ESG Risk Level          430 non-null    object
dtypes: float64(7), object(6)
memory usage: 51.2+ KB

In [11]:
# Step 5: Missing Value Summary
# Count missing values
df_clean.isnull().sum()

Symbol                      0
Name                        0
Sector                      1
Industry                    1
Full Time Employees         5
Total ESG Risk score       73
Environment Risk Score     73
Governance Risk Score      73
Social Risk Score          73
Controversy Level          73
Controversy Score         100
ESG Risk Percentile        73
ESG Risk Level             73
dtype: int64

In [12]:
# Handle Missing Value
# Fill missing numeric values with median
numeric_cols = [
    'Full Time Employees', 'Total ESG Risk score',
    'Environment Risk Score', 'Governance Risk Score',
    'Social Risk Score', 'Controversy Score',
    'ESG Risk Percentile'
]
df_clean[numeric_cols] = df_clean[numeric_cols].fillna(df_clean[numeric_cols].median())

In [13]:
# Fill missing categorical values with "Unknown"
categorical_cols = ['Sector', 'Industry', 'Controversy Level', 'ESG Risk Level']
df_clean[categorical_cols] = df_clean[categorical_cols].fillna('Unknown')

In [14]:
# Final check
df_clean.isnull().sum()

Symbol                    0
Name                      0
Sector                    0
Industry                  0
Full Time Employees       0
Total ESG Risk score      0
Environment Risk Score    0
Governance Risk Score     0
Social Risk Score         0
Controversy Level         0
Controversy Score         0
ESG Risk Percentile       0
ESG Risk Level            0
dtype: int64

In [15]:
# Save cleaned data as CSV
df_clean.to_csv('SP500_ESG_Cleaned.csv', index=False)